### ISSUE TITLE
Convert eagle files to gerber

### ISSUE THREAD

**Issue by inktrap** [electricityforprogress/BiodataSonificationBreadboardKit#8]
I would like to have a gerber file of the arduino breadboard-shield to upload to some pcb manufacturers to get a quote, e.g. pcbway which has a an online gerber view. Btw. I tried to place an order via your store for the feather-pcb, but it wouldn't accept my adress which is strange, I live in Germany.  So if I can't order the feather-pcb I would appreciate a gerber file of that as well (would be useful to have anyaways, right?). Btw., I would really find it unfair if someone re-used the designs for commercial purposes, but I guess [MIT](https://github.com/electricityforprogress/BiodataFeather/blob/master/LICENSE) would allow it.

I checked how to convert this (I am totally new to pcb design) and can open the `sch` and `brd` files with kicad and do an auto-matching of the layers, but the milling layer is not matched and I don't know how much of a problem that is and I also don't know if the auto-matching introduced any mistakes.

I would tend to build this the arduino way, because it seems much easier to get started with arduino than with feather, but regarding this project, the feather way seems to be much easier and less effort, also it offers more features out of the box, like wifi and bluetooth, whereas the arduino way is midi via a socket. Do you have any plans to add a [bluetooth](https://create.arduino.cc/projecthub/electropeak/getting-started-with-hc-05-bluetooth-module-arduino-e0ca81) or [wifi](https://www.arduino.cc/en/Guide/ArduinoWiFiShield) to that? I guess it wouldn't make that much sense because feather has it integrated already.

**Comment by inktrap** [comment]
Hey so I downloaded eagle and was able to convert these to gerber files and the various services happily accepted these. I am leaving this open and will wait for feedback from you. Perhaps you want to add the files yourself, or I could create a PR. Also it might help to add some recommendations how to order this (lead-free solder, aso.)?

**Comment by electricityforprogress** [comment]
Sorry the old Arduino Uno shield is out-dated and i will not be making any changes.  Just use the ESP32 Feather version.

Ha, there are a dozen companies who commercially use my designs and code, some providing attribution. 

I usually don't post gerber files because ... 1. If you don't know much about circuit board manufacture, then you can buy the circuit board directly from me 2. If you do know about circuit board manufacture then the process is trivial. 3. A user can do much more with a BRD and schematic file for remixing and changes.
